name = "ayu"
display-name = "Ayu"
description = "The Ayu theme"
version = "0.1.2"
author = "WalterOfNone"
icon = "ayu-icon.png"
repository = "https://github.com/walterofnone/ayu"
color-themes = ["ayu-dark.toml", "ayu-mirage.toml"]