name = "ayu"
display-name = "Ayu"
description = "The Ayu theme"
version = "0.1.1"
author = "WalterOfNone"
icon = "icon.png"
repository = "https://github.com/walterofnone/ayu"
color-themes = ["ayu-mirage.toml, ayu-dark.toml"]