name = "ayu"
display-name = "Ayu"
description = "The Ayu theme, now on lapce."
version = "0.1.0"
author = "walterofnone"
repository = "https://github.com/walterofnone/ayu"
themes = ["ayu-mirage.toml"]